### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by burque505** [syscomgo/omflow#7]
Hello, the program looks good! 
So far, I can mod omflow\settings.py (Windows) to get the login to show English.
Do you have any advice for me in translating the rest of the interface?
(It won't be good, my Chinese language skills are poor, but it could be a start).
A way to set the default language from the dashboard would be ideal. I will keep experimenting, and thank you.

**Comment by syscom-pen** [comment]
Thanks for your question.
However, we haven't finished the translation yet.But multi language in our roadmap
so the i18n already in the code and js files, 
you can translate locale file yourself:
in windows , you can use gettext to generate locale file
in linux , you can use django-admin makemessages -l  to generate locale file

**Comment by syscom-pen** [comment]
> 
> 
> Hello, the program looks good!
> So far, I can mod omflow\settings.py (Windows) to get the login to show English.
> Do you have any advice for me in translating the rest of the interface?
> (It won't be good, my Chinese language skills are poor, but it could be a start).
> A way to set the default language from the dashboard would be ideal. I will keep experimenting, and thank you.

Thanks for your question.
However, we haven't finished the translation yet.But multi language in our roadmap
so the i18n already in the code and js files,
you can translate locale file yourself:
in windows , you can use gettext to generate locale file
in linux , you can use django-admin makemessages -l to generate locale file

**Comment by syscom-pen** [comment]
1.1.0.0 is done , support Traditional Chinese, Simplified Chinese, English, Japanese
