### ISSUE TITLE
translate models field in english

### ISSUE THREAD

**Issue by youssriaboelseod** [syscomgo/omflow#9]
wao
its fantastic
thank you for your so cooperation for upload this idea
we will work with you for make it as global idea 

**Is your feature request related to a problem? Please describe.**
about models field in Japanese language its not understand from outside janban

**Describe the solution you'd like**
so i will translate it to English and i will send pull request for it ( if you accept it , that mean you accept my cooperation for imporve you project as i can"

**Describe alternatives you've considered**
or you can add lazy_translate to more language

**Additional context**
if you have any another idea for co opeation in my country kindly send it to my email
esmallah1@gmail.com

thanks 
youssri

**Comment by syscom-pen** [comment]
many many , thank you.
but i have a lot of bug will fixed.
this conflicts with your suggestion ...
